# @package _global_
output_dir: "/home/emir-machine/dev/runs/fmnist_kan_convs/"
dataset_path: "/home/emir-machine/dev/datasets/FashionMNIST/"
save_dir: "./weights/"
dataset_name: "fmnist"
model_name: "kanbaseline"
gradient_accumulation_steps: 1
mixed_precision: 'no'
epochs: 5
save_interval: 5
train_batch_size: 32
val_batch_size: 32
dataloader_num_workers: -1
seed: 472
device: 'cuda'
inference: false
model_path: none
max_train_steps: none

use_torch_compile: false
unpack_data: true

optim:
  type: 'AdamW'
  learning_rate: 1e-3
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-4
  adam_epsilon: 1e-8
  lr_warmup_steps: 1000
  lr_power: 0.2
  lr_end: 1e-7
  set_grads_to_none: false
  momentum: 0.9

loss:
  label_smoothing: 0.05