# @package _global_
# output_dir: "/home/emir-machine/dev/runs/fmnist_kan_convs/"
dataset_path: "/Users/emirulurak/Desktop/dev/myresearchs/kan/priv__/datasets/"
# logging_dir: "/home/emir-machine/dev/runs/fmnist_kan_convs/logs/"
save_dir: "./weights/"
model_name: "fmnist_kan_convs"
gradient_accumulation_steps: 1
mixed_precision: 'no'
epochs: 5
save_interval: 
train_batch_size: 32
val_batch_size: 32
dataloader_num_workers: 1
seed: 472
device: 'cpu'
max_train_steps: none
max_grad_norm: 2.

use_torch_compile: false
unpack_data: true

checkpointing_steps: 5000
checkpoints_total_limit: 1000
find_unused_parameters: false

metrics:
  report_type: 'classification'

model:
  groups: 1
  degree: 4
  width_scale: 1
  num_classes: 10
  is_moe: false

wandb:
  entity: 'None'
  project_name: 'cifar100-tune_eight'

optim:
  type: 'adamW'
  learning_rate: 5e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-4
  adam_epsilon: 1e-8
  lr_warmup_steps: 1000
  lr_power: 0.2
  lr_end: 1e-7
  set_grads_to_none: false

loss:
  label_smoothing: 0.05